# Copyright (c) 2025 Bivex
#
# Author: Bivex
# Available for contact via email: support@b-b.top
# For up-to-date contact information:
# https://github.com/bivex
#
# Created: 2025-12-18T12:28:34
# Last Updated: 2025-12-18T12:28:34
#
# Licensed under the MIT License.
# Commercial licensing available upon request.

# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-12-13T18:38:22+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import datetime
from enum import Enum, IntEnum
from ipaddress import IPv4Address
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Extra, Field, confloat, conint, constr, field_validator


class Money(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: confloat(ge=0.0, le=999999999.99) = Field(
        ..., description='Amount in the specified currency', example=25.5
    )
    currency: str = Field(
        ..., description='ISO 4217 currency code (3 uppercase letters)', example='USD'
    )

    @field_validator('currency')
    @classmethod
    def validate_currency(cls, v):
        import re
        if not re.match(r'^[A-Z]{3}$', v):
            raise ValueError('Currency must be exactly 3 uppercase letters')
        return v


class OfferPerformance(BaseModel):
    class Config:
        extra = Extra.forbid

    clicks: int = Field(..., example=1500)
    conversions: int = Field(..., example=45)
    revenue: Money
    cost: Money
    cr: float = Field(..., example=0.03)
    epc: Money
    roi: float = Field(..., example=2.15)


class OfferAutoPause(BaseModel):
    class Config:
        extra = Extra.forbid

    threshold: float = Field(..., example=0.02)
    minClicksBeforePause: int = Field(..., example=1000)


class OfferType(Enum):
    direct = 'direct'
    email = 'email'
    phone = 'phone'


class IsValid(IntEnum):
    integer_0 = 0
    integer_1 = 1


class FraudReason(Enum):
    bot_pattern_detected = 'bot_pattern_detected'
    missing_user_agent = 'missing_user_agent'
    ip_blacklisted = 'ip_blacklisted'
    user_agent_blocked = 'user_agent_blocked'
    suspicious_referrer_length = 'suspicious_referrer_length'
    forced_bot_detection = 'forced_bot_detection'


class PaginationLinks(BaseModel):
    first: Optional[AnyUrl] = Field(
        None, example='/api/v1/campaigns?page=1&pageSize=20'
    )
    prev: Optional[AnyUrl] = Field(None, example='/api/v1/campaigns?page=1&pageSize=20')
    next: Optional[AnyUrl] = Field(None, example='/api/v1/campaigns?page=2&pageSize=20')
    last: Optional[AnyUrl] = Field(None, example='/api/v1/campaigns?page=8&pageSize=20')


class Code(Enum):
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    NOT_FOUND = 'NOT_FOUND'
    CONFLICT = 'CONFLICT'
    INVARIANT_VIOLATION = 'INVARIANT_VIOLATION'
    UNAUTHENTICATED = 'UNAUTHENTICATED'
    UNAUTHORIZED = 'UNAUTHORIZED'
    METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED'
    NOT_ACCEPTABLE = 'NOT_ACCEPTABLE'
    UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE'
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'


class Error1(BaseModel):
    code: Optional[Code] = Field(
        None, description='Machine-readable error code', example='VALIDATION_ERROR'
    )
    message: Optional[str] = Field(
        None,
        description='Human-readable error message',
        example='Validation failed: name is required',
    )
    details: Optional[Dict[str, Any]] = Field(
        None, description='Optional object for detailed validation errors'
    )


class Error(BaseModel):
    error: Error1


class CampaignStatus(Enum):
    draft = 'draft'
    active = 'active'
    paused = 'paused'
    completed = 'completed'
    cancelled = 'cancelled'


class PageType(Enum):
    direct = 'direct'
    squeeze = 'squeeze'
    bridge = 'bridge'
    thank_you = 'thank_you'


class ConversionType(Enum):
    lead = 'lead'
    sale = 'sale'
    install = 'install'
    registration = 'registration'
    signup = 'signup'


class CostModel(Enum):
    CPA = 'CPA'
    CPC = 'CPC'
    CPM = 'CPM'


class CampaignSchedule(BaseModel):
    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None


class CampaignURLs(BaseModel):
    safePage: AnyUrl = Field(..., example='https://example.com/safe-landing')
    offerPage: AnyUrl = Field(..., example='https://example.com/offer')


class CampaignFinancial(BaseModel):
    costModel: CostModel
    payout: Money
    dailyBudget: Optional[Money] = None
    totalBudget: Optional[Money] = None
    spent: Money


class CampaignPerformance(BaseModel):
    clicks: int = Field(..., example=1250)
    conversions: int = Field(..., example=45)
    ctr: float = Field(..., example=0.032)
    cr: float = Field(..., example=0.036)
    epc: Money
    roi: float = Field(..., example=2.45)


class CampaignLinks(BaseModel):
    self: Optional[str] = Field(None, example='/api/v1/campaigns/camp_123')
    landingPages: Optional[str] = Field(
        None, example='/api/v1/campaigns/camp_123/landing-pages'
    )
    offers: Optional[str] = Field(None, example='/api/v1/campaigns/camp_123/offers')
    targeting: Optional[str] = Field(
        None, example='/api/v1/campaigns/camp_123/targeting'
    )
    analytics: Optional[str] = Field(
        None, example='/api/v1/campaigns/camp_123/analytics'
    )


class CampaignSummary(BaseModel):
    id: str = Field(..., example='camp_123')
    name: str = Field(..., example='Summer Sale Campaign')
    status: CampaignStatus
    performance: CampaignPerformance
    field_links: Optional[CampaignLinks] = Field(None, alias='_links')


class PaginationMeta(BaseModel):
    page: conint(ge=1) = Field(..., description='Current page number', example=1)
    limit: conint(ge=1, le=1000) = Field(
        ..., description='Number of items per page', example=50
    )
    total: conint(ge=0) = Field(
        ..., description='Total number of items available', example=250
    )
    totalPages: conint(ge=0) = Field(
        ..., description='Total number of pages', example=5
    )
    hasNext: bool = Field(..., description='Whether there is a next page', example=True)
    hasPrev: bool = Field(
        ..., description='Whether there is a previous page', example=False
    )


class Error2(BaseModel):
    field: str = Field(..., description='Field that failed validation', example='name')
    message: str = Field(
        ..., description='Validation error message', example='Name is required'
    )
    code: Optional[str] = Field(
        None, description='Validation error code', example='required'
    )


class ValidationError(BaseModel):
    type: str = Field(
        ..., description='Error type identifier', example='validation_error'
    )
    title: str = Field(
        ..., description='Human-readable error title', example='Validation Error'
    )
    status: int = Field(..., description='HTTP status code', example=400)
    detail: str = Field(
        ...,
        description='Detailed error description',
        example='The request contains invalid data',
    )
    instance: Optional[AnyUrl] = Field(
        None, description='URI reference to the resource', example='/campaigns/camp_123'
    )
    errors: Optional[List[Error2]] = Field(
        None, description='List of specific validation errors'
    )


class ClickValidationResponse(BaseModel):
    clickId: str = Field(
        ..., description='Unique click identifier', example='click_123456'
    )
    isValid: bool = Field(
        ..., description='Whether the click passes validation', example=True
    )
    fraudScore: confloat(ge=0.0, le=1.0) = Field(
        ..., description='Fraud risk score (0.0 = safe, 1.0 = high risk)', example=0.05
    )
    redirectUrl: Optional[AnyUrl] = Field(
        None,
        description='URL to redirect to if valid',
        example='https://affiliate.com/offer/123',
    )
    validationReason: Optional[str] = Field(
        None, description='Reason for validation result', example='passed_all_checks'
    )
    blockedReason: Optional[str] = Field(
        None, description='Reason why click was blocked (null if valid)'
    )
    campaignId: Optional[str] = Field(
        None, description='Associated campaign ID', example='camp_123'
    )
    landingPageId: Optional[str] = Field(
        None, description='Target landing page ID', example='lp_456'
    )
    offerId: Optional[str] = Field(
        None, description='Associated offer ID', example='offer_789'
    )


class Type(Enum):
    ip_block = 'ip_block'
    ua_block = 'ua_block'
    geo_block = 'geo_block'
    rate_limit = 'rate_limit'
    pattern_match = 'pattern_match'
    score_threshold = 'score_threshold'


class Action(Enum):
    block = 'block'
    flag = 'flag'
    score_increase = 'score_increase'
    redirect_safe = 'redirect_safe'


class RateLimit(BaseModel):
    requests_per_minute: Optional[conint(ge=1)] = Field(None, example=100)
    time_window_seconds: Optional[conint(ge=1)] = Field(None, example=60)


class Conditions(BaseModel):
    ip_addresses: Optional[List[IPv4Address]] = Field(
        None,
        description='IP addresses or CIDR ranges to block/flag',
        example=['192.168.1.1', '10.0.0.0/8'],
    )
    user_agents: Optional[List[str]] = Field(
        None, description='User agent patterns to match', example=['bot', 'crawler']
    )
    countries: Optional[List[str]] = Field(
        None, description='Country codes to restrict', example=['RU', 'CN']
    )
    rate_limit: Optional[RateLimit] = Field(
        None, description='Rate limiting configuration'
    )
    score_threshold: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None, description='Fraud score threshold for action', example=0.8
    )

    @field_validator('countries')
    @classmethod
    def validate_countries(cls, v):
        if v is None:
            return v
        import re
        for country in v:
            if not re.match(r'^[A-Z]{2}$', country):
                raise ValueError('Country codes must be exactly 2 uppercase letters')
        return v


class FraudRule(BaseModel):
    id: str = Field(..., description='Unique rule identifier', example='fraud_rule_001')
    name: str = Field(
        ...,
        description='Human-readable rule name',
        example='Block suspicious user agents',
    )
    type: Type = Field(
        ..., description='Type of fraud detection rule', example='ip_block'
    )
    action: Action = Field(
        ..., description='Action to take when rule matches', example='block'
    )
    conditions: Optional[Conditions] = Field(
        None, description='Rule-specific conditions'
    )
    priority: conint(ge=1, le=100) = Field(
        ..., description='Rule priority (higher = processed first)', example=50
    )
    isActive: bool = Field(
        ..., description='Whether the rule is currently active', example=True
    )
    createdAt: Optional[datetime] = Field(None, description='Rule creation timestamp')
    updatedAt: Optional[datetime] = Field(
        None, description='Rule last update timestamp'
    )


class FraudRuleCollection(BaseModel):
    status: str = Field(..., example='success')
    rules: List[FraudRule]
    pagination: Optional[PaginationMeta] = None


class TimeRange(BaseModel):
    startTime: datetime = Field(
        ..., description='Start of the 5-minute window', example='2024-01-15T10:00:00Z'
    )
    endTime: datetime = Field(
        ..., description='End of the 5-minute window', example='2024-01-15T10:05:00Z'
    )


class TopCampaign(BaseModel):
    campaignId: str = Field(..., example='camp_123')
    campaignName: str = Field(..., example='Summer Sale Campaign')
    clicks: int = Field(..., example=45)
    conversions: int = Field(..., example=8)


class TopLandingPage(BaseModel):
    landingPageId: str = Field(..., example='lp_456')
    pageName: str = Field(..., example='Main Squeeze Page')
    clicks: int = Field(..., example=67)
    conversions: int = Field(..., example=15)


class RealTimeAnalytics(BaseModel):
    timeRange: TimeRange = Field(..., description='Time window for real-time data')
    activeUsers: int = Field(
        ..., description='Number of active users in the last 5 minutes', example=1250
    )
    clicks: int = Field(
        ..., description='Total clicks in the last 5 minutes', example=89
    )
    conversions: int = Field(
        ..., description='Total conversions in the last 5 minutes', example=12
    )
    revenue: Money
    topCampaigns: List[TopCampaign] = Field(
        ...,
        description='Top 10 performing campaigns in the last 5 minutes',
        max_items=10,
    )
    topLandingPages: List[TopLandingPage] = Field(
        ...,
        description='Top 10 performing landing pages in the last 5 minutes',
        max_items=10,
    )
    fraudEvents: int = Field(
        ...,
        description='Number of fraud events detected in the last 5 minutes',
        example=3,
    )
    blockedClicks: int = Field(
        ..., description='Number of clicks blocked by fraud detection', example=7
    )


class LandingPagePerformance(BaseModel):
    impressions: int = Field(..., example=5000)
    clicks: int = Field(..., example=250)
    conversions: int = Field(..., example=15)
    ctr: float = Field(..., example=0.05)
    cr: float = Field(..., example=0.06)
    epc: Money


class CampaignOfferResource(BaseModel):
    id: str = Field(..., example='offer_789')
    campaignId: str = Field(..., example='camp_123')
    name: str = Field(..., example='Premium Product')
    url: AnyUrl = Field(..., example='https://affiliate.com/offer/123')
    offerType: OfferType
    weight: conint(ge=0) = Field(..., example=60)
    isActive: bool = Field(..., example=True)
    isControl: bool = Field(..., example=False)
    payout: Money
    revenueShare: Optional[confloat(ge=0.0, le=1.0)] = Field(None, example=0.15)
    costPerClick: Optional[Money] = None
    performance: Optional[OfferPerformance] = None
    autoPause: Optional[OfferAutoPause] = None
    externalId: Optional[str] = Field(None, example='AFF_123')
    partnerNetwork: Optional[str] = Field(None, example='MaxBounty')
    createdAt: datetime
    updatedAt: datetime


class Granularity(Enum):
    hour = 'hour'
    day = 'day'
    week = 'week'
    month = 'month'


class AnalyticsTimeRange(BaseModel):
    startDate: date_aliased = Field(..., example='2024-01-01')
    endDate: date_aliased = Field(..., example='2024-01-31')
    granularity: Granularity = Field(..., example='day')


class AnalyticsMetrics(BaseModel):
    clicks: int = Field(..., example=5000)
    uniqueClicks: int = Field(..., example=4800)
    conversions: int = Field(..., example=150)
    revenue: Money
    cost: Money
    ctr: float = Field(..., example=0.025)
    cr: float = Field(..., example=0.03)
    epc: Money
    roi: float = Field(..., example=2.15)


class DateMetrics(BaseModel):
    date: date_aliased = Field(..., example='2024-01-15')
    metrics: AnalyticsMetrics


class TrafficSourceMetrics(BaseModel):
    trafficSourceId: str = Field(..., example='ts_google')
    name: str = Field(..., example='Google Ads')
    metrics: AnalyticsMetrics


class LandingPageMetrics(BaseModel):
    landingPageId: str = Field(..., example='lp_456')
    name: str = Field(..., example='Main Landing Page')
    metrics: AnalyticsMetrics


class GeographyMetrics(BaseModel):
    country: str = Field(..., example='US')
    metrics: AnalyticsMetrics


class DeviceMetrics(BaseModel):
    device: str = Field(..., example='desktop')
    metrics: AnalyticsMetrics


class UpdateCampaignRequest(BaseModel):
    name: Optional[constr(min_length=1, max_length=255)] = None
    description: Optional[constr(max_length=1000)] = None
    whiteUrl: Optional[AnyUrl] = None
    blackUrl: Optional[AnyUrl] = None
    payout: Optional[Money] = None
    dailyBudget: Optional[Money] = None
    totalBudget: Optional[Money] = None
    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None


class From(BaseModel):
    id: Optional[int] = Field(None, example=123456789)
    username: Optional[str] = Field(None, example='john_doe')
    first_name: Optional[str] = Field(None, example='John')
    last_name: Optional[str] = Field(None, example='Doe')


class Chat(BaseModel):
    id: Optional[int] = Field(None, example=123456789)
    type: Optional[str] = Field(None, example='private')


class Message(BaseModel):
    message_id: Optional[int] = Field(None, example=123)
    from_: Optional[From] = Field(None, alias='from', description='Sender information')
    chat: Optional[Chat] = None
    date: Optional[int] = Field(None, description='Unix timestamp', example=1640995200)
    text: Optional[str] = Field(None, description='Message text', example='/start')


class TelegramWebhookRequest(BaseModel):
    update_id: int = Field(
        ..., description='Unique update identifier', example=123456789
    )
    message: Message = Field(..., description='Message object from Telegram')


class Status(Enum):
    success = 'success'
    error = 'error'
    skipped = 'skipped'


class Response(BaseModel):
    chat_id: Optional[int] = Field(None, example=123456789)
    text: Optional[str] = Field(None, example='👋 Добро пожаловать!')
    reply_markup: Optional[Dict[str, Any]] = Field(
        None, description='Inline keyboard markup'
    )


class TelegramWebhookResponse(BaseModel):
    status: Optional[Status] = Field(None, example='success')
    webhook_id: Optional[str] = Field(
        None,
        description='Internal webhook identifier',
        example='550e8400-e29b-41d4-a716-446655440000',
    )
    response: Optional[Response] = Field(
        None, description='Bot response to send back to Telegram'
    )
    message: Optional[str] = Field(
        None,
        description='Error message if status is error',
        example='Invalid update format',
    )


class EventType(Enum):
    page_view = 'page_view'
    click = 'click'
    form_submit = 'form_submit'
    form_start = 'form_start'
    form_complete = 'form_complete'
    scroll = 'scroll'
    time_spent = 'time_spent'
    conversion = 'conversion'
    purchase = 'purchase'
    signup = 'signup'
    download = 'download'
    share = 'share'
    search = 'search'
    video_play = 'video_play'
    video_complete = 'video_complete'
    custom = 'custom'


class EventTrackingRequest(BaseModel):
    event_type: EventType = Field(
        ..., description='Type of event being tracked', example='click'
    )
    event_name: str = Field(
        ..., description='Specific event name', example='cta_button_click'
    )
    user_id: Optional[str] = Field(
        None, description='Anonymous user identifier', example='user_a1b2c3d4'
    )
    session_id: Optional[str] = Field(
        None, description='Session identifier', example='session_123456'
    )
    click_id: Optional[str] = Field(
        None,
        description='Associated click ID from traffic tracking',
        example='123e4567-e89b-12d3-a456-426614174000',
    )
    campaign_id: Optional[int] = Field(
        None, description='Campaign identifier', example=123
    )
    landing_page_id: Optional[int] = Field(
        None, description='Landing page identifier', example=456
    )
    url: Optional[AnyUrl] = Field(
        None, description='Current page URL', example='https://example.com/landing-page'
    )
    referrer: Optional[AnyUrl] = Field(
        None, description='Referrer URL', example='https://facebook.com/ad/123'
    )
    properties: Optional[Dict[str, Any]] = Field(
        None,
        description='Custom event properties',
        example={'button_text': 'Buy Now', 'form_field': 'email', 'scroll_depth': 75},
    )


class Status1(Enum):
    success = 'success'
    error = 'error'


class EventTrackingResponse(BaseModel):
    status: Optional[Status1] = Field(None, example='success')
    event_id: Optional[str] = Field(
        None,
        description='Unique event identifier',
        example='550e8400-e29b-41d4-a716-446655440000',
    )
    categories: Optional[List[str]] = Field(
        None,
        description='Event categories for analytics',
        example=['interaction', 'cta_interaction'],
    )
    fraud_detected: Optional[bool] = Field(
        None, description='Whether fraudulent activity was detected', example=False
    )
    message: Optional[str] = Field(
        None,
        description='Error message if status is error',
        example='Invalid event data',
    )


class ConversionTrackingRequest(BaseModel):
    click_id: UUID = Field(
        ...,
        description='Click ID that led to this conversion',
        example='123e4567-e89b-12d3-a456-426614174000',
    )
    conversion_type: ConversionType = Field(
        ..., description='Type of conversion', example='sale'
    )
    conversion_value: Optional[Money] = Field(
        None, description='Revenue value of the conversion'
    )
    order_id: Optional[str] = Field(
        None,
        description='External order/transaction identifier',
        example='ORDER_123456',
    )
    product_id: Optional[str] = Field(
        None, description='Product or service identifier', example='product_789'
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Additional conversion data',
        example={
            'source': 'web_store',
            'payment_method': 'credit_card',
            'discount_applied': True,
        },
    )


class Status2(Enum):
    success = 'success'
    error = 'error'
    duplicate = 'duplicate'


class Attribution(BaseModel):
    attribution_model: Optional[str] = Field(None, example='last_click')
    attribution_confidence: Optional[float] = Field(None, example=0.9)
    time_to_conversion: Optional[float] = Field(
        None, description='Seconds between click and conversion', example=3600.5
    )
    touchpoints: Optional[int] = Field(None, example=1)


class ConversionTrackingResponse(BaseModel):
    status: Optional[Status2] = Field(None, example='success')
    conversion_id: Optional[str] = Field(
        None,
        description='Unique conversion identifier',
        example='550e8400-e29b-41d4-a716-446655440000',
    )
    attribution: Optional[Attribution] = Field(
        None, description='Attribution data for the conversion'
    )
    fraud_detected: Optional[bool] = Field(
        None, description='Whether fraudulent activity was detected', example=False
    )
    postback_triggered: Optional[bool] = Field(
        None, description='Whether postback notifications were triggered', example=True
    )
    message: Optional[str] = Field(
        None,
        description='Error message if status is error',
        example='Click ID not found',
    )


class Params(BaseModel):
    sub1: Optional[constr(max_length=255)] = Field(
        None,
        description='Level 1 tracking parameter (Creative/Ad ID)',
        example='fb_ad_15',
    )
    sub2: Optional[constr(max_length=255)] = Field(
        None,
        description='Level 2 tracking parameter (Traffic Source)',
        example='facebook',
    )
    sub3: Optional[constr(max_length=255)] = Field(
        None,
        description='Level 3 tracking parameter (Ad Set/Campaign Group)',
        example='prospecting',
    )
    sub4: Optional[constr(max_length=255)] = Field(
        None,
        description='Level 4 tracking parameter (Ad Version/Creative Type)',
        example='video1',
    )
    sub5: Optional[constr(max_length=255)] = Field(
        None,
        description='Level 5 tracking parameter (Audience/Keyword)',
        example='lookalike78',
    )
    click_id: Optional[constr(max_length=255)] = Field(
        None, description='Affiliate network click ID', example='USERCLICK123'
    )
    aff_sub: Optional[constr(max_length=255)] = Field(
        None, description='Primary affiliate sub-identifier'
    )
    aff_sub2: Optional[constr(max_length=255)] = Field(
        None, description='Secondary affiliate sub-identifier'
    )
    aff_sub3: Optional[constr(max_length=255)] = Field(
        None, description='Tertiary affiliate sub-identifier'
    )
    aff_sub4: Optional[constr(max_length=255)] = Field(
        None, description='Quaternary affiliate sub-identifier'
    )
    aff_sub5: Optional[constr(max_length=255)] = Field(
        None, description='Quinary affiliate sub-identifier'
    )


class ClickGenerationRequest(BaseModel):
    campaign_id: int = Field(
        ..., description='Campaign ID to attribute clicks to', example=123
    )
    base_url: AnyUrl = Field(
        ...,
        description='Base URL to add tracking parameters to',
        example='https://example.com/landing-page',
    )
    landing_page_id: Optional[int] = Field(
        None, description='Specific landing page ID to target', example=456
    )
    offer_id: Optional[int] = Field(
        None, description='Specific offer ID to target', example=789
    )
    params: Optional[Params] = Field(None, description='Tracking parameters to include')


class Variation(BaseModel):
    id: Optional[str] = Field(
        None, description='Unique identifier for this variation', example='variation_1'
    )
    name: Optional[str] = Field(
        None,
        description='Human-readable name for this variation',
        example='Facebook Prospecting',
    )
    landing_page_id: Optional[int] = Field(
        None, description='Landing page ID for this variation', example=456
    )
    offer_id: Optional[int] = Field(
        None, description='Offer ID for this variation', example=789
    )
    params: Optional[Dict[str, Any]] = Field(
        None,
        description='Tracking parameters for this variation',
        example={'sub1': 'fb_ad_15', 'sub2': 'facebook', 'sub3': 'prospecting'},
    )


class BulkClickGenerationRequest(BaseModel):
    campaign_id: int = Field(..., description='Campaign ID for all URLs', example=123)
    base_url: AnyUrl = Field(
        ...,
        description='Base URL for all variations',
        example='https://example.com/landing-page',
    )
    variations: List[Variation] = Field(
        ..., description='Array of parameter variations', max_items=100, min_items=1
    )


class Status3(Enum):
    success = 'success'
    error = 'error'


class ClickGenerationResponse(BaseModel):
    status: Optional[Status3] = Field(None, example='success')
    tracking_url: Optional[AnyUrl] = Field(
        None,
        description='Generated tracking URL',
        example='https://example.com/landing-page?cid=123&ts=1640995200&sub1=fb_ad_15&sub2=facebook',
    )
    campaign_id: Optional[int] = Field(
        None, description='Campaign ID used', example=123
    )
    params: Optional[Dict[str, Any]] = Field(
        None,
        description='Optimized tracking parameters used',
        example={
            'sub1': 'fb_ad_15',
            'sub2': 'facebook',
            '_generated_at': 1640995200,
            '_version': '1.0',
        },
    )
    landing_page_id: Optional[int] = Field(
        None, description='Landing page ID used', example=456
    )
    offer_id: Optional[int] = Field(None, description='Offer ID used', example=789)
    message: Optional[str] = Field(
        None,
        description='Error message if status is error',
        example='campaign_id must be a positive integer',
    )


class Result(BaseModel):
    id: Optional[str] = Field(
        None, description='Variation identifier', example='variation_1'
    )
    name: Optional[str] = Field(
        None, description='Variation name', example='Facebook Prospecting'
    )
    url: Optional[AnyUrl] = Field(
        None,
        description='Generated tracking URL (null if failed)',
        example='https://example.com/landing-page?cid=123&ts=1640995200&sub1=fb_ad_15',
    )
    params: Optional[Dict[str, Any]] = Field(
        None, description='Parameters used for this variation'
    )
    status: Optional[Status3] = Field(None, example='success')
    error: Optional[str] = Field(
        None,
        description='Error message if status is error',
        example='Invalid landing_page_id',
    )


class BulkClickGenerationResponse(BaseModel):
    status: Optional[Status3] = Field(None, example='success')
    total_variations: Optional[int] = Field(
        None, description='Total number of variations requested', example=3
    )
    successful: Optional[int] = Field(
        None, description='Number of successfully generated URLs', example=2
    )
    failed: Optional[int] = Field(
        None, description='Number of failed generations', example=1
    )
    results: Optional[List[Result]] = Field(
        None, description='Results for each variation'
    )
    message: Optional[str] = Field(
        None,
        description='General error message if status is error',
        example='Bulk generation failed',
    )


class GoalType(Enum):
    lead = 'lead'
    sale = 'sale'
    signup = 'signup'
    registration = 'registration'
    download = 'download'
    view = 'view'
    time_spent = 'time_spent'
    custom = 'custom'


class TriggerType(Enum):
    event = 'event'
    url = 'url'
    time = 'time'
    manual = 'manual'


class GoalResource(BaseModel):
    id: Optional[str] = Field(
        None,
        description='Unique goal identifier',
        example='goal_550e8400-e29b-41d4-a716-446655440000',
    )
    campaign_id: Optional[int] = Field(
        None, description='Campaign this goal belongs to', example=123
    )
    name: Optional[str] = Field(
        None, description='Goal name', example='Lead Form Submission'
    )
    description: Optional[str] = Field(
        None,
        description='Goal description',
        example='Track when visitors submit lead capture forms',
    )
    goal_type: Optional[GoalType] = Field(
        None, description='Type of conversion goal', example='lead'
    )
    trigger_type: Optional[TriggerType] = Field(
        None, description='How the goal is triggered', example='event'
    )
    trigger_config: Optional[Dict[str, Any]] = Field(
        None,
        description='Configuration for goal triggering',
        example={'event_type': 'form_submit', 'event_name': 'lead_form_submit'},
    )
    value_config: Optional[Dict[str, Any]] = Field(
        None,
        description='Configuration for goal value calculation',
        example={'fixed_value': 10.0},
    )
    is_active: Optional[bool] = Field(
        None, description='Whether goal is active', example=True
    )
    attribution_window_days: Optional[int] = Field(
        None, description='Days to attribute conversions to this goal', example=30
    )
    priority: Optional[int] = Field(
        None,
        description='Goal evaluation priority (higher = more important)',
        example=1,
    )
    tags: Optional[List[str]] = Field(
        None,
        description='Tags for categorization',
        example=['form', 'lead', 'conversion'],
    )
    created_at: Optional[datetime] = Field(None, description='Goal creation timestamp')
    updated_at: Optional[datetime] = Field(
        None, description='Goal last update timestamp'
    )


class CreateGoalRequest(BaseModel):
    campaign_id: int = Field(..., description='Campaign ID for the goal', example=123)
    name: constr(min_length=1, max_length=255) = Field(
        ..., description='Goal name', example='Lead Form Submission'
    )
    description: Optional[constr(max_length=1000)] = Field(
        None, description='Goal description'
    )
    goal_type: GoalType = Field(
        ..., description='Type of conversion goal', example='lead'
    )
    trigger_type: TriggerType = Field(
        ..., description='How the goal is triggered', example='event'
    )
    trigger_config: Optional[Dict[str, Any]] = Field(
        None,
        description='Configuration for goal triggering',
        example={'event_type': 'form_submit', 'event_name': 'lead_form_submit'},
    )
    value_config: Optional[Dict[str, Any]] = Field(
        None,
        description='Configuration for goal value calculation',
        example={'fixed_value': 10.0},
    )
    is_active: Optional[bool] = Field(True, description='Whether goal should be active')
    attribution_window_days: Optional[conint(ge=1, le=365)] = Field(
        30, description='Attribution window in days'
    )
    priority: Optional[conint(ge=1, le=100)] = Field(1, description='Goal priority')
    tags: Optional[List[str]] = Field(None, description='Tags for categorization')


class UpdateGoalRequest(BaseModel):
    name: Optional[constr(min_length=1, max_length=255)] = Field(
        None, description='Goal name'
    )
    description: Optional[constr(max_length=1000)] = Field(
        None, description='Goal description'
    )
    trigger_config: Optional[Dict[str, Any]] = Field(
        None, description='Configuration for goal triggering'
    )
    value_config: Optional[Dict[str, Any]] = Field(
        None, description='Configuration for goal value calculation'
    )
    is_active: Optional[bool] = Field(None, description='Whether goal is active')
    attribution_window_days: Optional[conint(ge=1, le=365)] = Field(
        None, description='Attribution window in days'
    )
    priority: Optional[conint(ge=1, le=100)] = Field(None, description='Goal priority')
    tags: Optional[List[str]] = Field(None, description='Tags for categorization')


class GoalTemplate(BaseModel):
    name: Optional[str] = Field(None, example='Lead Form Submission')
    description: Optional[str] = Field(
        None, example='Track when visitors submit lead capture forms'
    )
    goal_type: Optional[GoalType] = Field(None, example='lead')
    trigger_type: Optional[TriggerType] = Field(None, example='event')
    trigger_config: Optional[Dict[str, Any]] = Field(
        None, example={'event_type': 'form_submit', 'event_name': 'lead_form_submit'}
    )
    value_config: Optional[Dict[str, Any]] = Field(
        None, example={'value_field': 'lead_value'}
    )
    attribution_window_days: Optional[int] = Field(None, example=30)
    tags: Optional[List[str]] = Field(None, example=['form', 'lead', 'conversion'])


class Method(Enum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'


class PostbackConfig(BaseModel):
    url: AnyUrl = Field(
        ...,
        description='Postback URL to send notification to',
        example='https://affiliate-network.com/postback?click_id={click_id}&amount={revenue}',
    )
    method: Optional[Method] = Field(
        'GET', description='HTTP method to use for postback', example='GET'
    )
    headers: Optional[Dict[str, str]] = Field(
        None,
        description='Custom headers to include in postback request',
        example={
            'Authorization': 'Bearer your_token_here',
            'X-API-Key': 'your_api_key',
        },
    )
    payload: Optional[Dict[str, Any]] = Field(
        None,
        description='Request payload for POST/PUT methods (overrides URL parameters)',
        example={
            'click_id': '{click_id}',
            'conversion_type': '{conversion_type}',
            'revenue': '{revenue}',
            'currency': '{currency}',
        },
    )
    max_attempts: Optional[conint(ge=1, le=10)] = Field(
        3, description='Maximum number of delivery attempts', example=3
    )


class PostbackSendRequest(BaseModel):
    conversion_id: UUID = Field(
        ...,
        description='Conversion ID to send postback for',
        example='550e8400-e29b-41d4-a716-446655440000',
    )
    postback_config: PostbackConfig


class Status6(Enum):
    success = 'success'
    failed = 'failed'
    error = 'error'


class PostbackSendResponse(BaseModel):
    status: Optional[Status6] = Field(None, example='success')
    postback_id: Optional[str] = Field(
        None,
        description='Unique postback identifier',
        example='550e8400-e29b-41d4-a716-446655440000',
    )
    response_code: Optional[int] = Field(
        None, description='HTTP response code from postback endpoint', example=200
    )
    response_body: Optional[str] = Field(
        None, description='Response body from postback endpoint', example='OK'
    )
    error_message: Optional[str] = Field(
        None,
        description='Error message if delivery failed',
        example='Connection timeout',
    )
    attempt_count: Optional[int] = Field(
        None, description='Number of attempts made', example=1
    )
    message: Optional[str] = Field(
        None, description='General status message', example='Postback sent successfully'
    )


class OfferMetrics(BaseModel):
    class Config:
        extra = Extra.forbid

    offerId: str = Field(..., example='offer_123')
    name: str = Field(..., example='Summer Sale Offer')
    metrics: AnalyticsMetrics


class ClickRecord(BaseModel):
    id: UUID = Field(
        ...,
        description='Unique click identifier',
        example='123e4567-e89b-12d3-a456-426614174000',
    )
    cid: conint(ge=1, le=2147483647) = Field(
        ..., description='Campaign ID', example=123
    )
    ip: IPv4Address = Field(
        ..., description='Client IP address', example='192.168.1.100'
    )
    ua: constr(max_length=1000) = Field(
        ...,
        description='User agent string',
        example='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    )
    ref: Optional[AnyUrl] = Field(
        None, description='HTTP referrer URL', example='https://facebook.com/ad/123'
    )
    isValid: IsValid = Field(
        ...,
        description='Click validity flag (1=valid, 0=invalid/fraudulent)',
        example=1,
    )
    ts: conint(ge=0) = Field(
        ..., description='Unix timestamp of click', example=1640995200
    )
    sub1: Optional[constr(max_length=255)] = Field(
        None, description='Creative ID', example='fb_ad_15'
    )
    sub2: Optional[constr(max_length=255)] = Field(
        None, description='Traffic source', example='facebook'
    )
    sub3: Optional[constr(max_length=255)] = Field(
        None, description='Ad set/company', example='adset_12'
    )
    sub4: Optional[constr(max_length=255)] = Field(
        None, description='Ad version', example='video1'
    )
    sub5: Optional[constr(max_length=255)] = Field(
        None, description='Keyword/audience', example='lookalike78'
    )
    clickId: Optional[constr(max_length=255)] = Field(
        None, description='Click ID for postbacks', example='USERCLICK123'
    )
    affSub: Optional[constr(max_length=255)] = Field(
        None, description='Affiliate sub ID', example='aff_sub_123'
    )
    affSub2: Optional[constr(max_length=255)] = Field(
        None, description='Affiliate sub ID 2'
    )
    affSub3: Optional[constr(max_length=255)] = Field(
        None, description='Affiliate sub ID 3'
    )
    affSub4: Optional[constr(max_length=255)] = Field(
        None, description='Affiliate sub ID 4'
    )
    affSub5: Optional[constr(max_length=255)] = Field(
        None, description='Affiliate sub ID 5'
    )
    fraudScore: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None,
        description='Fraud probability score (0.0=legitimate, 1.0=fraudulent)',
        example=0.8,
    )
    fraudReason: Optional[FraudReason] = Field(
        None, description='Reason for fraud detection', example='bot_pattern_detected'
    )
    landingPageId: Optional[conint(ge=1)] = Field(
        None, description='ID of landing page used', example=456
    )
    campaignOfferId: Optional[conint(ge=1)] = Field(
        None, description='ID of offer used', example=789
    )
    trafficSourceId: Optional[conint(ge=1)] = Field(
        None, description='ID of traffic source', example=101
    )
    conversionType: Optional[ConversionType] = None


class ClickList(BaseModel):
    clicks: List[ClickRecord]
    total: int = Field(..., example=1500)
    limit: Optional[int] = Field(None, example=50)
    offset: Optional[int] = Field(None, example=0)


class Pagination(BaseModel):
    page: conint(ge=1) = Field(..., example=1)
    pageSize: conint(ge=1) = Field(..., example=20)
    totalItems: int = Field(..., example=150)
    totalPages: int = Field(..., example=8)
    hasNext: bool = Field(..., example=True)
    hasPrev: bool = Field(..., example=False)
    field_links: Optional[PaginationLinks] = Field(None, alias='_links')


class CampaignResource(BaseModel):
    id: str = Field(..., example='camp_123')
    name: str = Field(..., example='Summer Sale Campaign')
    description: Optional[str] = Field(None, example='High-converting summer promotion')
    status: CampaignStatus
    schedule: Optional[CampaignSchedule] = None
    urls: CampaignURLs
    financial: Optional[CampaignFinancial] = None
    performance: Optional[CampaignPerformance] = None
    createdAt: datetime
    updatedAt: datetime
    field_links: Optional[CampaignLinks] = Field(None, alias='_links')


class CampaignCollection(BaseModel):
    campaigns: List[CampaignSummary]
    pagination: Pagination


class LandingPageResource(BaseModel):
    id: str = Field(..., example='lp_456')
    campaignId: str = Field(..., example='camp_123')
    name: str = Field(..., example='Main Squeeze Page')
    url: AnyUrl = Field(..., example='https://example.com/page1')
    pageType: PageType
    weight: conint(ge=0) = Field(..., example=70)
    isActive: bool = Field(..., example=True)
    isControl: bool = Field(..., example=False)
    performance: Optional[LandingPagePerformance] = None
    createdAt: datetime
    updatedAt: datetime


class AnalyticsBreakdowns(BaseModel):
    byDate: Optional[List[DateMetrics]] = None
    byTrafficSource: Optional[List[TrafficSourceMetrics]] = None
    byLandingPage: Optional[List[LandingPageMetrics]] = None
    byOffer: Optional[List[OfferMetrics]] = None
    byGeography: Optional[List[GeographyMetrics]] = None
    byDevice: Optional[List[DeviceMetrics]] = None


class GoalCollection(BaseModel):
    goals: Optional[List[GoalResource]] = None
    total: Optional[int] = Field(None, description='Total number of goals', example=5)
    pagination: Optional[Pagination] = None


class CampaignAnalytics(BaseModel):
    campaignId: str = Field(..., example='camp_123')
    timeRange: AnalyticsTimeRange
    metrics: AnalyticsMetrics
    breakdowns: Optional[AnalyticsBreakdowns] = None
